accounts/urls.py
from django.urls import path
from .views import register, index, update_user, update_password

app_name = 'accounts'
urlpatterns = [
    path('', index, name='index'),
    path('registro/', register, name='register'),
    path('alterar-dados/', update_user, name='update_user'),
    path('alterar-senha/', update_password, name='update_password'),
]

catalog/urls.py
from django.urls import path
from . import views

app_name='catalog'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<str:slug>', views.category, name='category'),
    path('produto/<str:slug>', views.product, name='product'),
]

checkout/urls.py
from django.urls import path
from . import views

app_name='checkout'
urlpatterns = [
    path('carrinho/adicionar/<str:slug>/', views.create_cartItem, name='create_cartitem'),
    path('carrinho/', views.cart_item, name='cart_item'),
    path('finalizando/', views.checkout, name='checkout'),
    path('finalizando/<int:pk>/pagseguro', views.pag_seguro, name='pagseguro'),
    path('finalizando/<int:pk>/paypal', views.pay_pal, name='paypal'),
    path('meus-pedidos/', views.order_list, name='order_list'),
    path('meus-pedidos/<int:pk>/', views.order_detail, name='order_detail'),
    path('notificacoes/pagseguro', views.pagseguro_notification, name='pagseguro_notification'),
]

djangoecommerce/urls.py
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.urls import path, include

from core import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contato/', views.contact, name='contact'),
    path('entrar/', login, {'template_name': 'login.html'}, name='login'),
    path('conta/', include('accounts.urls')),
    path('sair/', logout, {'next_page': 'index'}, name='logout'),
    path('catalogo/', include('catalog.urls')),
    path('compras/', include('checkout.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('admin/', admin.site.urls),
]

checkout/models.py
from django.db import models
from catalog.models import Product
from django.conf import settings
from pagseguro import PagSeguro

class CartItemManager(models.Manager):

    def add_item(self, cart_key, product):
        if self.filter(cart_key=cart_key, product=product).exists():
            created = False
            cart_item = self.get(cart_key=cart_key, product=product)
            cart_item.quantity = cart_item.quantity + 1
            cart_item.save()
        else:
            created = True
            cart_item = CarItem.objects.create(
                cart_key=cart_key, product=product, price=product.price
            )
        return cart_item, created

class CarItem(models.Model):

    cart_key = models.CharField('Chave do Carrinho', max_length=40, db_index=True)
    product = models.ForeignKey(Product, verbose_name='Produto', null=True, on_delete=models.SET_NULL)
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    objects = CartItemManager()

    class Meta:
        verbose_name = 'Item do Carrinho'
        verbose_name_plural = 'Itens dos Carrinhos'
        unique_together = (('cart_key', 'product'),)

    def __str__(self):
        return '{} [{}]'.format(self.product, self.quantity)

class OrderManager(models.Manager):

    def create_order(self, user, cart_items):
        order = self.create(user=user)
        for cart_item in cart_items:
            order_item = OrderItem.objects.create(
                order=order, product=cart_item.product, quantity=cart_item.quantity,
                price=cart_item.price
            )
        return order

class Order(models.Model):
    STATUS_CHOICES = (
        (0, 'Aguardando pagamento'),
        (1, 'Concluída'),
        (2, 'Cancelada')
    )
    PAYMENT_OPTION_CHOICES = (
        ('deposit', 'Depósito'),
        ('pagseguro', 'PagSeguro'),
        ('paypal', 'PayPal')
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário', on_delete=models.CASCADE)
    status = models.IntegerField(
        'Situação', choices=STATUS_CHOICES, default=0, blank=True
    )
    payment_option = models.CharField(
        'Opção de pagamento', choices=PAYMENT_OPTION_CHOICES, max_length=20,
        default='deposit'
    )
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    objects = OrderManager()

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

    def __str__(self):
        return 'Pedido #{}'.format(self.pk)

    def products(self):
        # ids de todos os produtos desse pedido
        products_ids = self.itens.values_list('product')
        # retorna os produtos com os ids
        return Product.objects.filter(pk__in=products_ids)

    def total(self):
        aggregate_queryset = self.itens.aggregate(
            total=models.Sum(
            models.F('price') * models.F('quantity'),
            output_field=models.DecimalField())
        )
        return aggregate_queryset['total']

    def complete(self):
        self.status = 1
        self.save()

    def pagseguro(self):
        self.payment_option = 'pagseguro'
        self.save()
        pg = PagSeguro(
            email=settings.PAGSEGURO_EMAIL, token=settings.PAGSEGURO_TOKEN,
            config={'sandbox': settings.PAGSEGURO_SANDBOX}
        )
        pg.sender = {
            'email': self.user.email
        }
        pg.reference_prefix = None
        pg.shipping = None
        pg.reference = self.pk
        for item in self.itens.all():
            pg.items.append(
                {
                    'id': item.product.pk,
                    'description': item.product.name,
                    'quantity': item.quantity,
                    'amount': '%.2f' % item.price
                }
            )
        return pg

    def paypal(self):
        self.payment_option = 'paypal'
        self.save()
        paypal_dict = {
            'upload': '1',
            'business': settings.PAYPAL_EMAIL,
            'invoice': self.pk,
            'cmd': '_cart',
            'currency_code': 'BRL',
            'charset': 'utf-8',
        }
        index = 1
        for item in self.itens.all():
            paypal_dict['amount_{}'.format(index)] = '%.2f' % item.price
            paypal_dict['item_name_{}'.format(index)] = item.product.name
            paypal_dict['quantity_{}'.format(index)] = item.quantity
            index = index + 1
        return paypal_dict

    def pagseguro_update_status(self, status):
        if status == '3':
            self.status = 1
        elif status == '7':
            self.status = 2
        self.save()

class OrderItem(models.Model):
    order = models.ForeignKey(Order, verbose_name='Pedido', related_name='itens', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='Produto', null=True, on_delete=models.SET_NULL)
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'

    def __str__(self):
        return '[{}] {}'.format(self.order, self.product)

def post_save_cart_item(instance, **kwargs):
    if instance.quantity < 1:
        instance.delete()

models.signals.post_save.connect(
    post_save_cart_item, sender=CarItem, dispatch_uid='post_save_cart_item'
)

checkout/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import RedirectView, TemplateView, ListView, DetailView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import modelformset_factory
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from pagseguro import PagSeguro

from paypal.standard.forms import PayPalPaymentsForm
from paypal.standard.models import ST_PP_COMPLETED
from paypal.standard.ipn.signals import valid_ipn_received

from catalog.models import Product
from .models import CarItem, Order

class CreateCartItemView(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        product = get_object_or_404(Product, slug=self.kwargs['slug'])
        if self.request.session.session_key is None:
            self.request.session.save()
        cart_item, created = CarItem.objects.add_item(
            self.request.session.session_key, product
        )
        if created:
            messages.success(self.request, 'Produto adicionado com sucesso')
        else:
            messages.success(self.request, 'Produto atualizado com sucesso')

        return reverse('checkout:cart_item')

class CartItemView(TemplateView):
    template_name = 'checkout/cart.html'

    def get_formset(self, clear=False):
        CartItemFormSet = modelformset_factory(
            CarItem, fields=('quantity',), can_delete=True, extra=0
        )
        session_key = self.request.session.session_key
        if session_key:
            if clear:
                formset = CartItemFormSet(
                    queryset=CarItem.objects.filter(cart_key=session_key)
                )
            else:
                formset = CartItemFormSet(
                    queryset=CarItem.objects.filter(cart_key=session_key),
                    data=self.request.POST or None
                )
        else:
            formset = CartItemFormSet(queryset=CarItem.objects.none())
        return formset

    def get_context_data(self, **kwargs):
        context = super(CartItemView, self).get_context_data(**kwargs)
        context['formset'] = self.get_formset()
        return context

    def post(self, request, *args, **kwargs):
        formset = self.get_formset()
        context = self.get_context_data(**kwargs)

        if formset.is_valid():
            formset.save()
            messages.success(request, 'Carrinho atualizado com sucesso')
            context['formset'] = self.get_formset(clear=True)
        return self.render_to_response(context)

class CheckoutView(LoginRequiredMixin, TemplateView):
    template_name = 'checkout/checkout.html'

    def get(self, request, *args, **kwargs):
        session_key = request.session.session_key

        if session_key and CarItem.objects.filter(cart_key=session_key).exists():
            cart_items = CarItem.objects.filter(cart_key=session_key)
            order = Order.objects.create_order(
                user=request.user, cart_items=cart_items
            )
            cart_items.delete()
        else:
            messages.info(request, 'Não há itens no carrinho de compras')
            return redirect('checkout:cart_item')
        response = super(CheckoutView, self).get(request, *args, **kwargs)
        response.context_data['order'] = order
        return response

class OrderListView(LoginRequiredMixin, ListView):
    template_name = 'checkout/order_list.html'
    paginate_by = 10

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)

class OrderDetailView(LoginRequiredMixin, DetailView):
    template_name = 'checkout/order_detail.html'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)

class PagSeguroView(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        order_pk = self.kwargs.get('pk')
        order = get_object_or_404(
            Order.objects.filter(user=self.request.user), pk=order_pk
        )
        pg = order.pagseguro()
        pg.redirect_url = self.request.build_absolute_uri(
            reverse('checkout:order_detail', args=[order.pk])
        )
        pg.notification.url = self.request.build_absolute_uri(
            reverse('checkout:pagseguro_notification')
        )
        response = pg.checkout()
        return response.payment_url

@csrf_exempt
def pagseguro_notification(request):
    notification_code = request.POST.get('notificationCode', None)
    if notification_code:
        pg = PagSeguro(
            email=settings.PAGSEGURO_EMAIL, token=settings.PAGSEGURO_TOKEN,
            config={'sandbox': settings.PAGSEGURO_SANDBOX}
        )
        notification_data = pg.check_notification(notification_code)
        status = notification_data.status
        reference = notification_data.reference
        try:
            order = Order.objects.get(pk=reference)
        except Order.DoesNotExists:
            pass
        else:
            order.pagseguro_update_status(status)
    return HttpResponse('OK')

class PaypalView(LoginRequiredMixin, TemplateView):
    template_name = 'checkout/paypal.html'

    def get_context_data(self, **kwargs):
        context = super(PaypalView, self).get_context_data(**kwargs)
        order_pk = self.kwargs.get('pk')
        order = get_object_or_404(
            Order.objects.filter(user=self.request.user), pk=order_pk
        )
        paypal_dict = order.paypal()
        paypal_dict['return_url'] = self.request.build_absolute_uri(
            reverse('checkout:order_list')
        )
        paypal_dict['cancel_return'] = self.request.build_absolute_uri(
            reverse('checkout:order_list')
        )
        paypal_dict['notify_url'] = self.request.build_absolute_uri(
            reverse('paypal-ipn')
        )
        context['form'] = PayPalPaymentsForm(initial=paypal_dict)
        return context

def paypal_notification(sender, **kwargs):
    ipn_obj = sender
    if ipn_obj.payment_status == ST_PP_COMPLETED and \
        ipn_obj.receiver_emaiil == settings.PAYPAL_EMAIL:
        try:
            order = Order.objects.get(pk=ipn_obj.invoice)
            order.complete()
        except Order.DoesNotExists:
            pass

valid_ipn_received.connect(paypal_notification)

cart_item = CartItemView.as_view()
create_cartItem = CreateCartItemView.as_view()
checkout = CheckoutView.as_view()
order_list = OrderListView.as_view()
order_detail = OrderDetailView.as_view()
pag_seguro = PagSeguroView.as_view()
pay_pal = PaypalView.as_view()

checkout/templates/checkout/cart.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}
  Carrinho de compras | {{ block.super }}
{% endblock %}

{% block container %}
<ol class="breadcrumb">
      <li><a href="{% url 'accounts:index' %}">Início</a></li>
      <li class="active">Carrinho de Compras</li>
    </ol>
<div class="page-header">
	<h1>Carrinho de Compras</h1>
</div>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <form class="" action="" method="post">
          {% csrf_token %}
          {{ formset.management_form }}
          <table class="table table-bordered">
              <thead>
                <th>ID</th>
                <th>Nome</th>
	              <th>Preço</th>
                <th style="width: 10%;">Quantidade</th>
	              <th></th>
              </thead>
              <tbody>
                {% for form in formset %}
                <tr>
                  <td>{{ form.instance.product.pk }}</td>
                  <td>{{ form.instance.product }}</td>
                  <td>R$ {{ form.instance.price|floatformat:"2" }}</td>
			            <td>
                    {% render_field form.quantity class='form-control' %}
                  </td>
      						<td class="text-center">
      							<button type="submit" name="{{ form.DELETE.html_name }}"
                    value="on" class="btn btn-danger btn-sm">remover</button>
      						</td>
                  {{ form.id }}
                </tr>
                {% endfor %}
              </tbody>
            </table>
          <p class="text-right">
    				<a href="{% url 'catalog:product_list' %}" class="pull-left btn btn-default">Continuar Compras</a>
    				<button type="submit" class="btn btn-primary" name="button">Atualizar Carrinho</button></li>
    				<a href="{% url 'checkout:checkout' %}" class="btn btn-success">Finalizar Compra</a>
          </p>
        </form>
      </div>
    </div>
{% endblock %}

checkout/templates/checkout/checkout.html
{% extends "base.html" %}

{% block title %}
  Finalizando compra | {{ block.super }}
{% endblock %}

{% block container %}
  <ol class="breadcrumb">
    <li><a href="{% url 'index' %}">Início</a></li>
    <li><a href="{% url 'checkout:cart_item' %}">Carrinho de Compras</a></li>
    <li class="active">Finalização da Compra</li>
  </ol>
  <div class="page-header">
    <h1>Escolha a forma de pagamento</h1>
  </div>
  <div class="row">
    <div class="col-md-12">
      <p>Pedido #{{ order.pk }}</p>
    </div>
    <div class="col-md-4 col-md-offset-2">
      <a href="{% url 'checkout:pagseguro' order.pk %}" class="btn btn-success">Pagar com PagSeguro</a>
    </div>
    <div class="col-md-4">
      <a href="{% url 'checkout:paypal' order.pk %}" class="btn btn-primary">Pagar com Paypal</a>
    </div>
  </div>
{% endblock %}

checkout/templates/checkout/order_detail.html
{% extends "accounts/index.html" %}

{% block title %}
  Pedido #{{ object.pk }} | {{ block.super }}
{% endblock %}

{% block accounts_container %}
<h2>Pedido #{{ object.pk }}</h2>

<dl class="dl-horizontal">
  <dt>Total R$</dt>
  <dd>R$ {{ object.total|floatformat:"2" }}</dd>
  <dt>Situação</dt>
  <dd>{{ object.get_status_display }}</dd>
  <dt>Data</dt>
  <dd>{{ object.created|date:"d/m/y H:i"}}</dd>
  <dt>Meio de pagamento</dt>
  <dd>{{ object.get_payment_option_display }}</dd>
</dl>
<h3>Itens do pedido</h3>
{% for item in object.itens.all %}
  <dl class="dl-horizontal">
    <dt>Produto</dt>
    <dd>{{ item.product }}</dd>
    <dt>Quantidade</dt>
    <dd>{{ item.quantity }}</dd>
    <dt>Preçoc</dt>
    <dd>R$ {{ item.price|floatformat:"2"}}</dd>
  </dl>
{% endfor %}
{% endblock %}

checkout/templates/checkout/order_list.html
{% extends "accounts/index.html" %}
{% load pagination %}

{% block title %}
  Meus pedidos | {{ block.super }}
{% endblock %}

{% block accounts_container %}
<h2>Meus Pedidos</h2>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Produtos</th>
      <th>Situação</th>
      <th>Data</th>
    </tr>
  </thead>
  <tbody>
    {% for order in object_list %}
    <tr>
      <td><a href="{% url 'checkout:order_detail' order.pk %}">#{{ order.pk }}</a></td>
      <td>
        {% for product in order.products %}
          {{ product.name }}{% if not forloop.last %}<br />{% endif %}
        {% endfor %}
      </td>
      <td>{{ order.get_status_display }}</td>
      <td>{{ order.created|date:"d/m/Y"}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% pagination request paginator page_obj %}
{% endblock %}

checkout/templates/checkout/paypal.html
{% extends "base.html" %}

{% block title %}
Pagamento via Paypal
{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'index' %}">Início</a></li>
  <li><a href="{% url 'checkout:cart_item' %}">Carrinho de Compras</a></li>
  <li class="active">Pagamento via Paypal</li>
</ol>
<div class="page-header">
    <h1>Você está sendo redirecionado para o paypal</h1>
</div>
<div id="paypal" class="row">
    {{ form.render }}
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(function(){
        $("#paypal form").submit();
    });
</script>
{% endblock %}