accounts/urls.py
from django.urls import path
from .views import register, index, update_user, update_password

app_name = 'accounts'
urlpatterns = [
    path('', index, name='index'),
    path('registro/', register, name='register'),
    path('alterar-dados/', update_user, name='update_user'),
    path('alterar-senha/', update_password, name='update_password'),
]

catalog/urls.py
from django.urls import path
from . import views

app_name='catalog'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<str:slug>', views.category, name='category'),
    path('produto/<str:slug>', views.product, name='product'),
]

checkout/urls.py
from django.urls import path
from . import views

app_name='checkout'
urlpatterns = [
    path('carrinho/adicionar/<str:slug>/', views.create_cartItem, name='create_cartitem'),
    path('carrinho/', views.cart_item, name='cart_item'),
    path('finalizando/', views.checkout, name='checkout'),
    path('finalizando/<int:pk>/pagseguro', views.pag_seguro, name='pagseguro'),
    path('finalizando/<int:pk>/paypal', views.pay_pal, name='paypal'),
    path('meus-pedidos/', views.order_list, name='order_list'),
    path('meus-pedidos/<int:pk>/', views.order_detail, name='order_detail'),
    path('notificacoes/pagseguro', views.pagseguro_notification, name='pagseguro_notification'),
]

djangoecommerce/urls.py
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.urls import path, include

from core import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contato/', views.contact, name='contact'),
    path('entrar/', login, {'template_name': 'login.html'}, name='login'),
    path('conta/', include('accounts.urls')),
    path('sair/', logout, {'next_page': 'index'}, name='logout'),
    path('catalogo/', include('catalog.urls')),
    path('compras/', include('checkout.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
import re
from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin

class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Apelido / Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras, números '
                'e os caracteres: @/./+/-/_.',
                'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )
    name = models.CharField('Nome', max_length=100)
    email = models.EmailField('E-mail', unique=True)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import User

class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'name', 'email']

class UserAdminForm(ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'is_active', 'is_staff']

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView, UpdateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import reverse_lazy

from .models import User
from .forms import UserAdminCreationForm

class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/index.html'

class RegisterView(CreateView):
    model = User
    template_name = 'accounts/register.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('index')

class UpdateUserView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'accounts/update_user.html'
    fields = ['name', 'email']
    success_url = reverse_lazy('accounts:index')

    def get_object(self):
        return self.request.user

class UpdatePasswordView(LoginRequiredMixin, FormView):

    template_name = 'accounts/update_password.html'
    success_url = reverse_lazy('accounts:index')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(UpdatePasswordView, self).form_valid(form)

index = IndexView.as_view()
register = RegisterView.as_view()
update_user = UpdateUserView.as_view()
update_password = UpdatePasswordView.as_view()

accounts/templates/accounts/index.html
{% extends "base.html" %}

{% block title %}
  Minha Conta | {{ block.super }}
{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'accounts:index' %}">Início</a></li>
  <li class="active">Minha Conta</li>
</ol>
<div class="row">
    <div class="col-md-4">
        <div class="list-group">
          <a href="{% url 'accounts:index' %}" class="list-group-item active">Minha Conta</a>
          <a href="{% url 'accounts:update_user' %}" class="list-group-item">Alterar Dados</a>
          <a href="{% url 'accounts:update_password' %}" class="list-group-item">Alterar Senha</a>
          <a href="{% url 'checkout:order_list' %}" class="list-group-item">Meus Pedidos</a>
        </div>
    </div>
    <div class="col-md-8">
      {% block accounts_container %}
        <h2>Bem vindo {{ user }}</h2>
      {% endblock %}
    </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
  Registro | {{ block.super }}
{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Registro</h1>
        </div>
        <form class="form-horizontal" method="post">
          {% csrf_token %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error }}
            </div>
          {% endfor %}
            <fieldset>
              {% for field in form %}
                <div class="form-group {% if field.errors %} has-error{% endif %}">
                  <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                  <div class="col-md-9">
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                      <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
              {% endfor %}

              <div class="form-group">
                <div class="col-md-9 col-md-offset-3">
                  <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
              </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/update_password.html
{% extends "accounts/index.html" %}
{% load widget_tweaks %}

{% block title %}
  Alterar senha
{% endblock %}

{% block accounts_container %}
  <h2>Alterar senha</h2>

  <form class="form-horizontal" method="post">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">
        {{ error }}
      </div>
    {% endfor %}
    <fieldset>
      {% for field in form %}
        <div class="form-group {% if field.errors %} has-error{% endif %}">
          <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
          <div class="col-md-9">
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
              <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
      {% endfor %}

      <div class="form-group">
        <div class="col-md-9 col-md-offset-3">
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </div>
    </fieldset>
  </form>
{% endblock %}

accounts/templates/accounts/update_user.html
{% extends "accounts/index.html" %}
{% load widget_tweaks %}

{% block title %}
  Alterar dados
{% endblock %}

{% block accounts_container %}
  <h2>Alterar dados</h2>

  <form class="form-horizontal" method="post">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">
        {{ error }}
      </div>
    {% endfor %}
    <fieldset>
      {% for field in form %}
        <div class="form-group {% if field.errors %} has-error{% endif %}">
          <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
          <div class="col-md-9">
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
              <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
      {% endfor %}

      <div class="form-group">
        <div class="col-md-9 col-md-offset-3">
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </div>
    </fieldset>
  </form>
{% endblock %}